### ISSUE TITLE
"make check" fails

### ISSUE THREAD

**Issue by mwhudson** [zatrazz/glibc-tools#1]
I guess this project doesn't currently have any tests but the top level Makefile defines a check: target, that fails like so:

```
(ubuntu/jammy)mwhudson@anduril:~/src/pkg/glibc-tools$ make check
make: *** No rule to make target 'check-libSegFault', needed by 'check'.  Stop.
```

Adding a dummy "check-libSegFault" target to libSegFault/Dir.mk makes this pass.

**Comment by zatrazz** [comment]
Thanks, I I have fixed it on 23fd2b927e159a8a32905f3fea0af3743349133c.
